# Generated by Django 4.1.13 on 2023-12-29 20:49

from django.db import migrations, models
import users.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=users.storage_backend.ProfilePictureStorage(), upload_to='profile_pics'),
        ),
    ]
