version: "3.7"

x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    command: "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so


  tailwind:
    <<: *default-app
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: anno_db
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
